name: .NET build and test

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - "src/**"
      - "tests/**"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/dotnet-build-and-test.yaml"
      - "src/**"
      - "tests/**"

jobs:
  build-and-test:
    uses: Nexus-Mods/NexusMods.App.Meta/.github/workflows/dotnet-build-and-test-with-osx.yaml@b9253edb6f621c60726984ec4d8646f63b85d1bb
